name: Frontend CI

on:
  push:
    branches: [ main, develop ] # Или какие у вас там основные ветки
    paths:
      - 'step_flow/frontend_web/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'step_flow/frontend_web/**'

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./step_flow/frontend_web
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Укажите вашу версию Node.js
        cache: 'npm'
        cache-dependency-path: step_flow/frontend_web/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint # Убедитесь, что у вас есть скрипт lint в package.json

    - name: Build
      run: npm run build # Убедитесь, что у вас есть скрипт build в package.json

    - name: Test
      run: |
        # Создадим пока пустой тест, чтобы пайплайн не падал
        # Убедитесь, что у вас настроен тестовый фреймворк (например, Jest, Vitest)
        # и есть скрипт test в package.json
        # Пример для Vitest:
        echo "import { expect, test } from 'vitest';\ntest('example test', () => {\n  expect(1 + 1).toBe(2);\n});" > src/App.test.tsx
        npm run test --if-present # Запускаем тесты, если скрипт есть